# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5eb9d1e18b1756c1f030f3ae8860f26d1f1441a36c5e3c5a05b551dfd2b7a143e798ae1e436de263a45d4c1bf1ca5f24055976abf658d573a6202981162d50e

test:
  secret_key_base: 084519aad10954c2f41f28974905b5f562db8ec033a84d1e47f647f03d32838f44bbbae600f89a40e02d604204f3c3e51aeed2e02698723e4b45cbbddff8b397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
